### ISSUE TITLE
Edit menu disappeared and right click disabled when installing Weighted Switch Controller

### ISSUE THREAD

**Issue by andycrossproxama** [Blazemeter/jmeter-bzm-plugins#1]
I recently installed Jmeter 3.2 and a bunch of plugins.  

When installing the WSC plugin, I found that the Edit menu became greyed out and right click was disabled.

```
2017-06-19 11:46:02,218 ERROR o.a.j.g.u.MenuFactory: Error initializing menus in static bloc, check configuration if using 3rd party libraries
java.lang.NoSuchMethodError: kg.apc.jmeter.gui.Grid.<init>(Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/Class;[Ljava/lang/Object;Ljavax/swing/JTable;)V
	at com.blazemeter.jmeter.control.WeightedSwitchControllerGui.init(WeightedSwitchControllerGui.java:57) ~[jmeter-plugins-wsc-0.2.jar:?]
	at com.blazemeter.jmeter.control.WeightedSwitchControllerGui.<init>(WeightedSwitchControllerGui.java:30) ~[jmeter-plugins-wsc-0.2.jar:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_131]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_131]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_131]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_131]
	at org.apache.jmeter.gui.util.MenuFactory.initializeMenus(MenuFactory.java:505) ~[ApacheJMeter_core.jar:3.2 r1790748]
	at org.apache.jmeter.gui.util.MenuFactory.<clinit>(MenuFactory.java:169) ~[ApacheJMeter_core.jar:3.2 r1790748]
	at org.apache.jmeter.control.gui.TestPlanGui.createPopupMenu(TestPlanGui.java:93) ~[ApacheJMeter_core.jar:3.2 r1790748]
	at org.apache.jmeter.gui.tree.JMeterTreeNode.createPopupMenu(JMeterTreeNode.java:156) ~[ApacheJMeter_core.jar:3.2 r1790748]
	at org.apache.jmeter.gui.action.EditCommand.doAction(EditCommand.java:46) ~[ApacheJMeter_core.jar:3.2 r1790748]
	at org.apache.jmeter.gui.action.ActionRouter.performAction(ActionRouter.java:74) ~[ApacheJMeter_core.jar:3.2 r1790748]
	at org.apache.jmeter.gui.action.ActionRouter.lambda$actionPerformed$0(ActionRouter.java:59) ~[ApacheJMeter_core.jar:3.2 r1790748]
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) [?:1.8.0_131]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756) [?:1.8.0_131]
	at java.awt.EventQueue.access$500(EventQueue.java:97) [?:1.8.0_131]
	at java.awt.EventQueue$3.run(EventQueue.java:709) [?:1.8.0_131]
	at java.awt.EventQueue$3.run(EventQueue.java:703) [?:1.8.0_131]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_131]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) [?:1.8.0_131]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726) [?:1.8.0_131]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [?:1.8.0_131]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [?:1.8.0_131]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [?:1.8.0_131]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:1.8.0_131]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [?:1.8.0_131]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [?:1.8.0_131]
2017-06-19 11:46:02,221 ERROR o.a.j.JMeter: Uncaught exception: 
java.lang.NoSuchMethodError: kg.apc.jmeter.gui.Grid.<init>(Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/Class;[Ljava/lang/Object;Ljavax/swing/JTable;)V
	at com.blazemeter.jmeter.control.WeightedSwitchControllerGui.init(WeightedSwitchControllerGui.java:57) ~[jmeter-plugins-wsc-0.2.jar:?]
	at com.blazemeter.jmeter.control.WeightedSwitchControllerGui.<init>(WeightedSwitchControllerGui.java:30) ~[jmeter-plugins-wsc-0.2.jar:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_131]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_131]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_131]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_131]
	at org.apache.jmeter.gui.util.MenuFactory.initializeMenus(MenuFactory.java:505) ~[ApacheJMeter_core.jar:3.2 r1790748]
	at org.apache.jmeter.gui.util.MenuFactory.<clinit>(MenuFactory.java:169) ~[ApacheJMeter_core.jar:3.2 r1790748]
	at org.apache.jmeter.control.gui.TestPlanGui.createPopupMenu(TestPlanGui.java:93) ~[ApacheJMeter_core.jar:3.2 r1790748]
	at org.apache.jmeter.gui.tree.JMeterTreeNode.createPopupMenu(JMeterTreeNode.java:156) ~[ApacheJMeter_core.jar:3.2 r1790748]
	at org.apache.jmeter.gui.action.EditCommand.doAction(EditCommand.java:46) ~[ApacheJMeter_core.jar:3.2 r1790748]
	at org.apache.jmeter.gui.action.ActionRouter.performAction(ActionRouter.java:74) ~[ApacheJMeter_core.jar:3.2 r1790748]
	at org.apache.jmeter.gui.action.ActionRouter.lambda$actionPerformed$0(ActionRouter.java:59) ~[ApacheJMeter_core.jar:3.2 r1790748]
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) ~[?:1.8.0_131]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756) ~[?:1.8.0_131]
	at java.awt.EventQueue.access$500(EventQueue.java:97) ~[?:1.8.0_131]
	at java.awt.EventQueue$3.run(EventQueue.java:709) ~[?:1.8.0_131]
	at java.awt.EventQueue$3.run(EventQueue.java:703) ~[?:1.8.0_131]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_131]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) ~[?:1.8.0_131]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726) ~[?:1.8.0_131]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [?:1.8.0_131]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [?:1.8.0_131]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [?:1.8.0_131]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:1.8.0_131]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [?:1.8.0_131]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [?:1.8.0_131]
2017-06-19 11:46:02,247 ERROR o.a.j.JMeter: Uncaught exception: 
java.lang.NoClassDefFoundError: Could not initialize class org.apache.jmeter.gui.util.MenuFactory
	at org.apache.jmeter.control.gui.TestPlanGui.createPopupMenu(TestPlanGui.java:93) ~[ApacheJMeter_core.jar:3.2 r1790748]
	at org.apache.jmeter.gui.tree.JMeterTreeNode.createPopupMenu(JMeterTreeNode.java:156) ~[ApacheJMeter_core.jar:3.2 r1790748]
	at org.apache.jmeter.gui.action.EditCommand.doAction(EditCommand.java:46) ~[ApacheJMeter_core.jar:3.2 r1790748]
	at org.apache.jmeter.gui.action.ActionRouter.performAction(ActionRouter.java:74) ~[ApacheJMeter_core.jar:3.2 r1790748]
	at org.apache.jmeter.gui.action.ActionRouter.lambda$actionPerformed$0(ActionRouter.java:59) ~[ApacheJMeter_core.jar:3.2 r1790748]
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) ~[?:1.8.0_131]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756) ~[?:1.8.0_131]
	at java.awt.EventQueue.access$500(EventQueue.java:97) ~[?:1.8.0_131]
	at java.awt.EventQueue$3.run(EventQueue.java:709) ~[?:1.8.0_131]
	at java.awt.EventQueue$3.run(EventQueue.java:703) ~[?:1.8.0_131]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_131]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) ~[?:1.8.0_131]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726) ~[?:1.8.0_131]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [?:1.8.0_131]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [?:1.8.0_131]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [?:1.8.0_131]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:1.8.0_131]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [?:1.8.0_131]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [?:1.8.0_131]
2017-06-19 11:46:12,912 ERROR o.a.j.JMeter: Uncaught exception: 
java.lang.NoClassDefFoundError: Could not initialize class org.apache.jmeter.gui.util.MenuFactory
	at org.apache.jmeter.control.gui.TestPlanGui.createPopupMenu(TestPlanGui.java:93) ~[ApacheJMeter_core.jar:3.2 r1790748]
	at org.apache.jmeter.gui.tree.JMeterTreeNode.createPopupMenu(JMeterTreeNode.java:156) ~[ApacheJMeter_core.jar:3.2 r1790748]
	at org.apache.jmeter.gui.tree.JMeterTreeListener.displayPopUp(JMeterTreeListener.java:237) ~[ApacheJMeter_core.jar:3.2 r1790748]
	at org.apache.jmeter.gui.tree.JMeterTreeListener.mousePressed(JMeterTreeListener.java:182) ~[ApacheJMeter_core.jar:3.2 r1790748]
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:280) ~[?:1.8.0_131]
	at java.awt.Component.processMouseEvent(Component.java:6530) ~[?:1.8.0_131]
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324) ~[?:1.8.0_131]
	at java.awt.Component.processEvent(Component.java:6298) ~[?:1.8.0_131]
	at java.awt.Container.processEvent(Container.java:2236) ~[?:1.8.0_131]
	at java.awt.Component.dispatchEventImpl(Component.java:4889) ~[?:1.8.0_131]
	at java.awt.Container.dispatchEventImpl(Container.java:2294) ~[?:1.8.0_131]
	at java.awt.Component.dispatchEvent(Component.java:4711) ~[?:1.8.0_131]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888) ~[?:1.8.0_131]
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4522) ~[?:1.8.0_131]
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466) ~[?:1.8.0_131]
	at java.awt.Container.dispatchEventImpl(Container.java:2280) ~[?:1.8.0_131]
	at java.awt.Window.dispatchEventImpl(Window.java:2746) ~[?:1.8.0_131]
	at java.awt.Component.dispatchEvent(Component.java:4711) ~[?:1.8.0_131]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) ~[?:1.8.0_131]
	at java.awt.EventQueue.access$500(EventQueue.java:97) ~[?:1.8.0_131]
	at java.awt.EventQueue$3.run(EventQueue.java:709) ~[?:1.8.0_131]
	at java.awt.EventQueue$3.run(EventQueue.java:703) ~[?:1.8.0_131]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_131]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) ~[?:1.8.0_131]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90) ~[?:1.8.0_131]
	at java.awt.EventQueue$4.run(EventQueue.java:731) ~[?:1.8.0_131]
	at java.awt.EventQueue$4.run(EventQueue.java:729) ~[?:1.8.0_131]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_131]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) ~[?:1.8.0_131]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) ~[?:1.8.0_131]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [?:1.8.0_131]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [?:1.8.0_131]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [?:1.8.0_131]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:1.8.0_131]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [?:1.8.0_131]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [?:1.8.0_131]
```

**Comment by artem-fedorov** [comment]
Hello,

What version of  jmeter-plugins-cmn-jmeter-0.*.jar installed in jmeter/lib folder? For WSC v0.2 need cmn lib version 0.5. If in your folder installed early version then try to use 0.5 [(link to download)](https://search.maven.org/remotecontent?filepath=kg/apc/jmeter-plugins-cmn-jmeter/0.5/jmeter-plugins-cmn-jmeter-0.5.jar) 

Can you describe how you installed plugins? Using Plugins Manager? and what is it version? Or maybe you have got more than one version of  jmeter-plugins-cmn-jmeter-0.*.jar files in jmeter/lib folder?

Thanks

**Comment by andycrossproxama** [comment]
Ah, thanks, that's done the job.  I'd missed that on the release notes.

I was running jmeter-plugins-cmn-jmeter-0.4.jar

Everything was installed fresh using the plugins manager.
